UPDATE calibration_gas_inventory SET sort_order = 1 WHERE site_name = 'WTC' AND unit_no = '1' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 2 WHERE site_name = 'WTC' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 3 WHERE site_name = 'WTC' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 4 WHERE site_name = 'WTC' AND unit_no = '1' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 5 WHERE site_name = 'WTC' AND unit_no = '2' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 6 WHERE site_name = 'WTC' AND unit_no = '2' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 7 WHERE site_name = 'WTC' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 8 WHERE site_name = 'WTC' AND unit_no = '2' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 9 WHERE site_name = 'WTC' AND unit_no = '3' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 10 WHERE site_name = 'WTC' AND unit_no = '3' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 11 WHERE site_name = 'WTC' AND unit_no = '3' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 12 WHERE site_name = 'WTC' AND unit_no = '3' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 13 WHERE site_name = 'LG화학 나주공장 KFC' AND unit_no = 'AT-9601' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 14 WHERE site_name = 'LG화학 나주공장 KFC' AND unit_no = 'AT-9601' AND gas_name = 'NO 402ppm';
UPDATE calibration_gas_inventory SET sort_order = 15 WHERE site_name = 'LG화학 나주공장 KFC' AND unit_no = 'AT-9601' AND gas_name = 'NO2 400ppm';
UPDATE calibration_gas_inventory SET sort_order = 16 WHERE site_name = 'LG화학 나주공장 KFC' AND unit_no = 'AT7301A' AND gas_name = '-';
UPDATE calibration_gas_inventory SET sort_order = 17 WHERE site_name = 'LG화학 나주공장 KFC' AND unit_no = 'AT7501A' AND gas_name = '-';
UPDATE calibration_gas_inventory SET sort_order = 18 WHERE site_name = 'LG화학 나주공장 KFC' AND unit_no = 'AT7701A' AND gas_name = 'NOx';
UPDATE calibration_gas_inventory SET sort_order = 19 WHERE site_name = 'LG화학 나주공장 KFC' AND unit_no = 'AT7701A' AND gas_name = 'NH3';
UPDATE calibration_gas_inventory SET sort_order = 20 WHERE site_name = 'LS전선' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 21 WHERE site_name = 'LS전선' AND unit_no = '1' AND gas_name = 'NO/SO2 200/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 22 WHERE site_name = 'OCI포항' AND unit_no = 'Tar(#2)' AND gas_name = 'NO/SO2/CO Zero';
UPDATE calibration_gas_inventory SET sort_order = 23 WHERE site_name = 'OCI포항' AND unit_no = 'Tar(#2)' AND gas_name = 'NO/SO2 200/200ppm';
UPDATE calibration_gas_inventory SET sort_order = 24 WHERE site_name = 'OCI포항' AND unit_no = 'Tar(#2)' AND gas_name = 'CO 500ppm (비전송)';
UPDATE calibration_gas_inventory SET sort_order = 25 WHERE site_name = 'OCI포항' AND unit_no = 'Tar(#2)' AND gas_name = 'O2 Span';
UPDATE calibration_gas_inventory SET sort_order = 26 WHERE site_name = 'OCI포항' AND unit_no = 'Tar(#3)' AND gas_name = 'NO/SO2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 27 WHERE site_name = 'OCI포항' AND unit_no = 'Tar(#3)' AND gas_name = 'NO/SO2 200/200ppm';
UPDATE calibration_gas_inventory SET sort_order = 28 WHERE site_name = 'OCI포항' AND unit_no = 'Tar(#3)' AND gas_name = 'CO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 29 WHERE site_name = 'OCI포항' AND unit_no = 'Tar(#3)' AND gas_name = 'O2 Span';
UPDATE calibration_gas_inventory SET sort_order = 30 WHERE site_name = 'OCI포항' AND unit_no = '카본(#28)' AND gas_name = 'NO/SO2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 31 WHERE site_name = 'OCI포항' AND unit_no = '카본(#28)' AND gas_name = 'NO/SO2 600/600ppm';
UPDATE calibration_gas_inventory SET sort_order = 32 WHERE site_name = 'OCI포항' AND unit_no = '카본(#28)' AND gas_name = 'O2 Span';
UPDATE calibration_gas_inventory SET sort_order = 33 WHERE site_name = 'OCI포항' AND unit_no = 'PAP(#19)' AND gas_name = 'NO/SO2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 34 WHERE site_name = 'OCI포항' AND unit_no = 'PAP(#19)' AND gas_name = 'NO/SO2 200/100ppm';
UPDATE calibration_gas_inventory SET sort_order = 35 WHERE site_name = 'OCI포항' AND unit_no = 'PAP(#19)' AND gas_name = 'O2 Span (비전송)';
UPDATE calibration_gas_inventory SET sort_order = 36 WHERE site_name = 'OCI포항' AND unit_no = 'Dust' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 37 WHERE site_name = 'GS동해전력' AND unit_no = '1' AND gas_name = 'NO/SO2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 38 WHERE site_name = 'GS동해전력' AND unit_no = '1' AND gas_name = 'NO/SO2 200/200ppm';
UPDATE calibration_gas_inventory SET sort_order = 39 WHERE site_name = 'GS동해전력' AND unit_no = '1' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 40 WHERE site_name = 'GS동해전력' AND unit_no = '1' AND gas_name = 'O2 Span';
UPDATE calibration_gas_inventory SET sort_order = 41 WHERE site_name = 'GS동해전력' AND unit_no = '1' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 42 WHERE site_name = 'GS동해전력' AND unit_no = '2' AND gas_name = 'NO/SO2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 43 WHERE site_name = 'GS동해전력' AND unit_no = '2' AND gas_name = 'NO/SO2 200/200ppm';
UPDATE calibration_gas_inventory SET sort_order = 44 WHERE site_name = 'GS동해전력' AND unit_no = '2' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 45 WHERE site_name = 'GS동해전력' AND unit_no = '2' AND gas_name = 'O2 Span';
UPDATE calibration_gas_inventory SET sort_order = 46 WHERE site_name = 'GS동해전력' AND unit_no = '2' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 47 WHERE site_name = 'KEP' AND unit_no = '41(30톤)' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 48 WHERE site_name = 'KEP' AND unit_no = '41(30톤)' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 49 WHERE site_name = 'KEP' AND unit_no = '41(30톤)' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 50 WHERE site_name = 'KEP' AND unit_no = '41(30톤)' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 51 WHERE site_name = 'KEP' AND unit_no = '57(80톤)' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 52 WHERE site_name = 'KEP' AND unit_no = '57(80톤)' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 53 WHERE site_name = 'KEP' AND unit_no = '57(80톤)' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 54 WHERE site_name = 'KEP' AND unit_no = '57(80톤)' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 55 WHERE site_name = 'KEP' AND unit_no = '48(100톤)' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 56 WHERE site_name = 'KEP' AND unit_no = '48(100톤)' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 57 WHERE site_name = 'KEP' AND unit_no = '48(100톤)' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 58 WHERE site_name = 'KEP' AND unit_no = '48(100톤)' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 59 WHERE site_name = 'KEP' AND unit_no = '#6(921M)' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 60 WHERE site_name = 'KEP' AND unit_no = '#6(921M)' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 61 WHERE site_name = 'KEP' AND unit_no = '#6(921M)' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 62 WHERE site_name = 'KEP' AND unit_no = '#6(921M)' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 63 WHERE site_name = 'KEP' AND unit_no = '#7(921L)' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 64 WHERE site_name = 'KEP' AND unit_no = '#7(921L)' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 65 WHERE site_name = 'KEP' AND unit_no = '#7(921L)' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 66 WHERE site_name = 'KEP' AND unit_no = '#7(921L)' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 67 WHERE site_name = 'KEP' AND unit_no = '#8(921P)' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 68 WHERE site_name = 'KEP' AND unit_no = '#8(921P)' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 69 WHERE site_name = 'KEP' AND unit_no = '#8(921P)' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 70 WHERE site_name = 'KEP' AND unit_no = '#8(921P)' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 71 WHERE site_name = '계룡소각장' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 72 WHERE site_name = '계룡소각장' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 73 WHERE site_name = '계룡소각장' AND unit_no = '1' AND gas_name = 'HCL 50ppm';
UPDATE calibration_gas_inventory SET sort_order = 74 WHERE site_name = '계룡소각장' AND unit_no = '1' AND gas_name = 'NO/SO2/CO 200/100/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 75 WHERE site_name = '금강공업 (음성)' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 76 WHERE site_name = '금강공업 (음성)' AND unit_no = '1' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 77 WHERE site_name = '금강공업 (음성)' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 78 WHERE site_name = '금강공업 (음성)' AND unit_no = '2' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 79 WHERE site_name = '금산군 소각장' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 80 WHERE site_name = '금산군 소각장' AND unit_no = '1' AND gas_name = 'NO/SO2/CO 200/200/600ppm';
UPDATE calibration_gas_inventory SET sort_order = 81 WHERE site_name = '금산군 소각장' AND unit_no = '1' AND gas_name = 'HCL 50ppm';
UPDATE calibration_gas_inventory SET sort_order = 82 WHERE site_name = '금산군 소각장' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 83 WHERE site_name = '금산군 소각장' AND unit_no = '1' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 84 WHERE site_name = '어프로티움 울산제3공장' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 85 WHERE site_name = '어프로티움 울산제3공장' AND unit_no = '1' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 86 WHERE site_name = '어프로티움 울산제3공장' AND unit_no = '1' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 87 WHERE site_name = '어프로티움 울산제3공장' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 88 WHERE site_name = '어프로티움 울산제3공장' AND unit_no = '3신규분' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 89 WHERE site_name = '어프로티움 울산제3공장' AND unit_no = '3신규분' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 90 WHERE site_name = '어프로티움 울산제3공장' AND unit_no = '3신규분' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 91 WHERE site_name = '어프로티움 울산제3공장' AND unit_no = '3신규분' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 92 WHERE site_name = '어프로티움 울산제2공장' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 93 WHERE site_name = '어프로티움 울산제2공장' AND unit_no = '1' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 94 WHERE site_name = '어프로티움 울산제2공장' AND unit_no = '1' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 95 WHERE site_name = '어프로티움 울산제2공장' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 96 WHERE site_name = '동서식품' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 97 WHERE site_name = '동서식품' AND unit_no = '1' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 98 WHERE site_name = '동서식품' AND unit_no = '1' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 99 WHERE site_name = '동서식품' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 100 WHERE site_name = '동양환경' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 101 WHERE site_name = '동양환경' AND unit_no = '2' AND gas_name = 'NO/SO2/CO 200/100/250ppm';
UPDATE calibration_gas_inventory SET sort_order = 102 WHERE site_name = '동양환경' AND unit_no = '2' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 103 WHERE site_name = '동양환경' AND unit_no = '2' AND gas_name = 'HCL 50ppm';
UPDATE calibration_gas_inventory SET sort_order = 104 WHERE site_name = '동양환경' AND unit_no = '2' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 105 WHERE site_name = '동우화인켐' AND unit_no = '33' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 106 WHERE site_name = '동우화인켐' AND unit_no = '33' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 107 WHERE site_name = '동우화인켐' AND unit_no = '33' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 108 WHERE site_name = '동우화인켐' AND unit_no = '33' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 109 WHERE site_name = '동일산업' AND unit_no = '5' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 110 WHERE site_name = '동일산업' AND unit_no = '5' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 111 WHERE site_name = '동일제강' AND unit_no = '18' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 112 WHERE site_name = '동일제강' AND unit_no = '18' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 113 WHERE site_name = '동일제강' AND unit_no = '19' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 114 WHERE site_name = '동일제강' AND unit_no = '19' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 115 WHERE site_name = '동일제강' AND unit_no = '36' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 116 WHERE site_name = '동일제강' AND unit_no = '36' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 117 WHERE site_name = '동일제강' AND unit_no = '38' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 118 WHERE site_name = '동일제강' AND unit_no = '38' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 119 WHERE site_name = '동일제강' AND unit_no = '38' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 120 WHERE site_name = '동일제강' AND unit_no = '38' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 121 WHERE site_name = '동일제강' AND unit_no = '41' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 122 WHERE site_name = '동일제강' AND unit_no = '41' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 123 WHERE site_name = '동일제강' AND unit_no = '47' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 124 WHERE site_name = '동일제강' AND unit_no = '47' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 125 WHERE site_name = '동희오토 서산공장' AND unit_no = '30' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 126 WHERE site_name = '동희오토 서산공장' AND unit_no = '30' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 127 WHERE site_name = '동희오토 서산공장' AND unit_no = '30' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 128 WHERE site_name = '동희오토 서산공장' AND unit_no = '3' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 129 WHERE site_name = '동희오토 서산공장' AND unit_no = '3' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 130 WHERE site_name = '드림아스콘' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 131 WHERE site_name = '드림아스콘' AND unit_no = '1' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 132 WHERE site_name = '드림아스콘' AND unit_no = '1' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 133 WHERE site_name = '드림아스콘' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 134 WHERE site_name = '드림아스콘' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 135 WHERE site_name = '드림아스콘' AND unit_no = '2' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 136 WHERE site_name = '드림아스콘' AND unit_no = '2' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 137 WHERE site_name = '드림아스콘' AND unit_no = '2' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 138 WHERE site_name = '모나리자 전주공장' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 139 WHERE site_name = '모나리자 전주공장' AND unit_no = '1' AND gas_name = 'NO/SO2 200/200ppm';
UPDATE calibration_gas_inventory SET sort_order = 140 WHERE site_name = '모나리자 전주공장' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 141 WHERE site_name = '모나리자 전주공장' AND unit_no = '1' AND gas_name = 'HCL 50ppm';
UPDATE calibration_gas_inventory SET sort_order = 142 WHERE site_name = '무림에스피 대구공장' AND unit_no = '7' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 143 WHERE site_name = '무림에스피 대구공장' AND unit_no = '7' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 144 WHERE site_name = '무림에스피 대구공장' AND unit_no = '7' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 145 WHERE site_name = '무림에스피 대구공장' AND unit_no = '7' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 146 WHERE site_name = '무림에스피 대구공장' AND unit_no = '8' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 147 WHERE site_name = '무림에스피 대구공장' AND unit_no = '8' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 148 WHERE site_name = '무림에스피 대구공장' AND unit_no = '8' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 149 WHERE site_name = '무림에스피 대구공장' AND unit_no = '8' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 150 WHERE site_name = '대륜발전' AND unit_no = '1' AND gas_name = 'N2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 151 WHERE site_name = '대륜발전' AND unit_no = '1' AND gas_name = 'NO 100ppm';
UPDATE calibration_gas_inventory SET sort_order = 152 WHERE site_name = '대륜발전' AND unit_no = '1' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 153 WHERE site_name = '대륜발전' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 154 WHERE site_name = '대륜발전' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 155 WHERE site_name = '대륜발전' AND unit_no = '2' AND gas_name = 'NO 100ppm';
UPDATE calibration_gas_inventory SET sort_order = 156 WHERE site_name = '대륜발전' AND unit_no = '2' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 157 WHERE site_name = '대륜발전' AND unit_no = '2' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 158 WHERE site_name = '부국산업' AND unit_no = '12' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 159 WHERE site_name = '부국산업' AND unit_no = '12' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 160 WHERE site_name = '부국산업' AND unit_no = '12' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 161 WHERE site_name = '부국산업' AND unit_no = '22' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 162 WHERE site_name = '부국산업' AND unit_no = '22' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 163 WHERE site_name = '부국산업' AND unit_no = '22' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 164 WHERE site_name = '성합' AND unit_no = '2' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 165 WHERE site_name = '성합' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 166 WHERE site_name = '성합' AND unit_no = '3' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 167 WHERE site_name = '성합' AND unit_no = '3' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 168 WHERE site_name = '성합' AND unit_no = '5' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 169 WHERE site_name = '성합' AND unit_no = '5' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 170 WHERE site_name = '성합' AND unit_no = '11' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 171 WHERE site_name = '성합' AND unit_no = '11' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 172 WHERE site_name = '삼보산업 창원' AND unit_no = '5' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 173 WHERE site_name = '삼보산업 창원' AND unit_no = '5' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 174 WHERE site_name = '삼양사 인천 1공장' AND unit_no = '1' AND gas_name = 'NO, SO2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 175 WHERE site_name = '삼양사 인천 1공장' AND unit_no = '1' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 176 WHERE site_name = '삼양사 인천 1공장' AND unit_no = '1' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 177 WHERE site_name = '삼양사 인천 1공장' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 178 WHERE site_name = '삼현' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 179 WHERE site_name = '삼현' AND unit_no = '2' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 180 WHERE site_name = '삼현' AND unit_no = '2' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 181 WHERE site_name = '삼현' AND unit_no = '2' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 182 WHERE site_name = '삼현' AND unit_no = '3' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 183 WHERE site_name = '삼현' AND unit_no = '3' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 184 WHERE site_name = '삼현' AND unit_no = '3' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 185 WHERE site_name = '삼현' AND unit_no = '3' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 186 WHERE site_name = '삼현' AND unit_no = '9(구 8호기)' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 187 WHERE site_name = '삼현' AND unit_no = '9(구 8호기)' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 188 WHERE site_name = '삼현' AND unit_no = '9(구 8호기)' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 189 WHERE site_name = '삼현' AND unit_no = '9(구 8호기)' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 190 WHERE site_name = '삼현 (신규)' AND unit_no = '10' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 191 WHERE site_name = '삼현 (신규)' AND unit_no = '10' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 192 WHERE site_name = '성훈엔지니어링' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 193 WHERE site_name = '성훈엔지니어링' AND unit_no = '1' AND gas_name = 'NO/SO2 400/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 194 WHERE site_name = '성훈엔지니어링' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 195 WHERE site_name = '성훈엔지니어링' AND unit_no = '2' AND gas_name = 'NO/SO2 400/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 196 WHERE site_name = '성훈엔지니어링' AND unit_no = '3' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 197 WHERE site_name = '성훈엔지니어링' AND unit_no = '3' AND gas_name = 'NO/SO2 400/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 198 WHERE site_name = '성훈엔지니어링' AND unit_no = '14' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 199 WHERE site_name = '성훈엔지니어링' AND unit_no = '14' AND gas_name = 'NO/SO2 400/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 200 WHERE site_name = '성훈엔지니어링' AND unit_no = '15' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 201 WHERE site_name = '성훈엔지니어링' AND unit_no = '15' AND gas_name = 'NO/SO2 400/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 202 WHERE site_name = '배터리솔루션즈' AND unit_no = '1' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 203 WHERE site_name = '배터리솔루션즈' AND unit_no = '1' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 204 WHERE site_name = '배터리솔루션즈' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 205 WHERE site_name = '배터리솔루션즈' AND unit_no = '1' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 206 WHERE site_name = '배터리솔루션즈' AND unit_no = '2' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 207 WHERE site_name = '배터리솔루션즈' AND unit_no = '2' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 208 WHERE site_name = '배터리솔루션즈' AND unit_no = '2' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 209 WHERE site_name = '배터리솔루션즈' AND unit_no = '2' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 210 WHERE site_name = '수완에너지' AND unit_no = '1' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 211 WHERE site_name = '수완에너지' AND unit_no = '1' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 212 WHERE site_name = '수완에너지' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 213 WHERE site_name = '수완에너지' AND unit_no = '1' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 214 WHERE site_name = '수완에너지' AND unit_no = '2' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 215 WHERE site_name = '수완에너지' AND unit_no = '2' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 216 WHERE site_name = '수완에너지' AND unit_no = '2' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 217 WHERE site_name = '수완에너지' AND unit_no = '2' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 218 WHERE site_name = '수원하수슬러지 처리시설' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 219 WHERE site_name = '수원하수슬러지 처리시설' AND unit_no = '1' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 220 WHERE site_name = '쌍용C&B' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 221 WHERE site_name = '쌍용C&B' AND unit_no = '1' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 222 WHERE site_name = '쌍용C&B' AND unit_no = '1' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 223 WHERE site_name = '쌍용C&B' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 224 WHERE site_name = '쌍용C&B' AND unit_no = '1' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 225 WHERE site_name = '쌍용C&B' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 226 WHERE site_name = '쌍용C&B' AND unit_no = '2' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 227 WHERE site_name = '쌍용C&B' AND unit_no = '2' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 228 WHERE site_name = '쌍용C&B' AND unit_no = '2' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 229 WHERE site_name = '쌍용C&B' AND unit_no = '2' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 230 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 231 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '1' AND gas_name = 'NO 100ppm';
UPDATE calibration_gas_inventory SET sort_order = 232 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '1' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 233 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 234 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 235 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '2' AND gas_name = 'NO 100ppm';
UPDATE calibration_gas_inventory SET sort_order = 236 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '2' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 237 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '2' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 238 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '3' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 239 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '3' AND gas_name = 'NO 100ppm';
UPDATE calibration_gas_inventory SET sort_order = 240 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '3' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 241 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '3' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 242 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '4' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 243 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '4' AND gas_name = 'NO 100ppm';
UPDATE calibration_gas_inventory SET sort_order = 244 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '4' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 245 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '4' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 246 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '5' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 247 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '5' AND gas_name = 'NO 100ppm';
UPDATE calibration_gas_inventory SET sort_order = 248 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '5' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 249 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '5' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 250 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '6' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 251 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '6' AND gas_name = 'NO 100ppm';
UPDATE calibration_gas_inventory SET sort_order = 252 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '6' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 253 WHERE site_name = '씨엔씨티에너지 학하CES' AND unit_no = '6' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 254 WHERE site_name = '여천NCC 1공장' AND unit_no = '' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 255 WHERE site_name = '여천NCC 3공장' AND unit_no = '' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 256 WHERE site_name = '여천NCC 4공장' AND unit_no = '' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 257 WHERE site_name = '오뚜기 대풍공장' AND unit_no = '54' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 258 WHERE site_name = '오뚜기 대풍공장' AND unit_no = '54' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 259 WHERE site_name = '오뚜기 대풍공장' AND unit_no = '62(SCR)' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 260 WHERE site_name = '오뚜기 대풍공장' AND unit_no = '62(SCR)' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 261 WHERE site_name = '오라이온코리아' AND unit_no = 'D boiler' AND gas_name = '-';
UPDATE calibration_gas_inventory SET sort_order = 262 WHERE site_name = '오라이온코리아' AND unit_no = '#2 RTO' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 263 WHERE site_name = '오라이온코리아' AND unit_no = '#2 RTO' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 264 WHERE site_name = '오라이온코리아' AND unit_no = '#2 RTO' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 265 WHERE site_name = '오라이온코리아' AND unit_no = '#1 RTO' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 266 WHERE site_name = '오라이온코리아' AND unit_no = '#2 RTO' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 267 WHERE site_name = '일진전기' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 268 WHERE site_name = '일진전기' AND unit_no = '1' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 269 WHERE site_name = '일진전기' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 270 WHERE site_name = '일진전기' AND unit_no = '2' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 271 WHERE site_name = '전북대학교병원' AND unit_no = '1' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 272 WHERE site_name = '전북대학교병원' AND unit_no = '1' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 273 WHERE site_name = '전북대학교병원' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 274 WHERE site_name = '전북대학교병원' AND unit_no = '1' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 275 WHERE site_name = '한국주철관공업' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 276 WHERE site_name = '한국주철관공업' AND unit_no = '2' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 277 WHERE site_name = '한국주철관공업' AND unit_no = '9' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 278 WHERE site_name = '한국주철관공업' AND unit_no = '9' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 279 WHERE site_name = '한국주철관공업' AND unit_no = '12' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 280 WHERE site_name = '한솔제지 대전' AND unit_no = '1(호프만)' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 281 WHERE site_name = '한솔제지 대전' AND unit_no = '1(호프만)' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 282 WHERE site_name = '한솔제지 대전' AND unit_no = '1(호프만)' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 283 WHERE site_name = '한솔제지 대전' AND unit_no = '2(혐기성)' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 284 WHERE site_name = '한솔제지 대전' AND unit_no = '2(혐기성)' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 285 WHERE site_name = '한솔제지 대전' AND unit_no = '2(혐기성)' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 286 WHERE site_name = '한솔제지 대전' AND unit_no = '3' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 287 WHERE site_name = '한솔제지 대전' AND unit_no = '3' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 288 WHERE site_name = '한솔제지 대전' AND unit_no = '3' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 289 WHERE site_name = '한솔제지 대전' AND unit_no = '5' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 290 WHERE site_name = '한솔제지 대전' AND unit_no = '5' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 291 WHERE site_name = '한솔제지 대전' AND unit_no = '5' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 292 WHERE site_name = '한솔제지 천안' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 293 WHERE site_name = '한솔제지 천안' AND unit_no = '1' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 294 WHERE site_name = '한솔제지 천안' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 295 WHERE site_name = '현대성우캐스팅' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 296 WHERE site_name = '현대성우캐스팅' AND unit_no = '1' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 297 WHERE site_name = '현대성우캐스팅' AND unit_no = '2(1공장)' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 298 WHERE site_name = '현대성우캐스팅' AND unit_no = '2(1공장)' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 299 WHERE site_name = '현대성우캐스팅' AND unit_no = '3(2공장)(칩용해로)' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 300 WHERE site_name = '현대성우캐스팅' AND unit_no = '3(2공장)(칩용해로)' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 301 WHERE site_name = '현대성우캐스팅' AND unit_no = '4(2공장)(Ladle)' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 302 WHERE site_name = '현대성우캐스팅' AND unit_no = '4(2공장)(Ladle)' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 303 WHERE site_name = '현성세라믹' AND unit_no = '24' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 304 WHERE site_name = '현성세라믹' AND unit_no = '24' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 305 WHERE site_name = '현성세라믹' AND unit_no = '24' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 306 WHERE site_name = '현성세라믹' AND unit_no = '25' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 307 WHERE site_name = '현성세라믹' AND unit_no = '25' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 308 WHERE site_name = '휴스틸' AND unit_no = '5' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 309 WHERE site_name = '휴스틸' AND unit_no = '5' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 310 WHERE site_name = '휴스틸' AND unit_no = '13' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 311 WHERE site_name = '휴스틸' AND unit_no = '13' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 312 WHERE site_name = '영화금속' AND unit_no = '4(SCR)' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 313 WHERE site_name = '영화금속' AND unit_no = '4(SCR)' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 314 WHERE site_name = '금강공업 언양' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 315 WHERE site_name = '금강공업 언양' AND unit_no = '1' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 316 WHERE site_name = '디알액시온 원산' AND unit_no = '3' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 317 WHERE site_name = '디알액시온 원산' AND unit_no = '3' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 318 WHERE site_name = '롯데패키징솔루션즈 평택' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 319 WHERE site_name = '롯데패키징솔루션즈 평택' AND unit_no = '1' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 320 WHERE site_name = '롯데패키징솔루션즈 평택' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 321 WHERE site_name = '롯데패키징솔루션즈 평택' AND unit_no = '2' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 322 WHERE site_name = '영월빛드림' AND unit_no = '' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 323 WHERE site_name = '영월빛드림' AND unit_no = '' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 324 WHERE site_name = '영월빛드림' AND unit_no = '' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 325 WHERE site_name = '롯데패키징솔루션즈 진천' AND unit_no = '9' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 326 WHERE site_name = '롯데패키징솔루션즈 진천' AND unit_no = '9' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 327 WHERE site_name = '태평양금속' AND unit_no = '11' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 328 WHERE site_name = '태평양금속' AND unit_no = '11' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 329 WHERE site_name = '태평양금속' AND unit_no = '12' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 330 WHERE site_name = '태평양금속' AND unit_no = '12' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 331 WHERE site_name = '태평양금속' AND unit_no = '13' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 332 WHERE site_name = '태평양금속' AND unit_no = '13' AND gas_name = 'NO/SO2 500/500ppm';
UPDATE calibration_gas_inventory SET sort_order = 333 WHERE site_name = '삼일씨엔에스' AND unit_no = '3' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 334 WHERE site_name = '삼일씨엔에스' AND unit_no = '3' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 335 WHERE site_name = '삼일씨엔에스' AND unit_no = '3' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 336 WHERE site_name = '삼일씨엔에스' AND unit_no = '3' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 337 WHERE site_name = '이구산업' AND unit_no = '#A28' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 338 WHERE site_name = '이구산업' AND unit_no = '#A28' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 339 WHERE site_name = '이구산업' AND unit_no = '#A28' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 340 WHERE site_name = '이구산업' AND unit_no = '#A30' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 341 WHERE site_name = '이구산업' AND unit_no = '#A30' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 342 WHERE site_name = '이구산업' AND unit_no = '#A30' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 343 WHERE site_name = '디에스우일바이오' AND unit_no = '1' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 344 WHERE site_name = '디에스우일바이오' AND unit_no = '1' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 345 WHERE site_name = '디에스우일바이오' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 346 WHERE site_name = 'AMMK' AND unit_no = 'A7' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 347 WHERE site_name = 'AMMK' AND unit_no = 'A7' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 348 WHERE site_name = 'AMMK' AND unit_no = 'A7' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 349 WHERE site_name = 'AMMK' AND unit_no = 'A7' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 350 WHERE site_name = '김포발전-TMS' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 351 WHERE site_name = '김포발전-TMS' AND unit_no = '1' AND gas_name = 'NO 50ppm';
UPDATE calibration_gas_inventory SET sort_order = 352 WHERE site_name = '김포발전-TMS' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 353 WHERE site_name = '김포발전-SCR' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 354 WHERE site_name = '김포발전-SCR' AND unit_no = '1' AND gas_name = 'NO 50ppm';
UPDATE calibration_gas_inventory SET sort_order = 355 WHERE site_name = '김포발전-SCR' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 356 WHERE site_name = 'GS EPS' AND unit_no = '7(복합3호기)' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 357 WHERE site_name = 'GS EPS' AND unit_no = '7(복합3호기)' AND gas_name = 'NO 50ppm';
UPDATE calibration_gas_inventory SET sort_order = 358 WHERE site_name = 'GS EPS' AND unit_no = '7(복합3호기)' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 359 WHERE site_name = 'GS EPS' AND unit_no = '8(복합4호기)' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 360 WHERE site_name = 'GS EPS' AND unit_no = '8(복합4호기)' AND gas_name = 'NO 50ppm';
UPDATE calibration_gas_inventory SET sort_order = 361 WHERE site_name = 'GS EPS' AND unit_no = '8(복합4호기)' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 362 WHERE site_name = '삼우 2공장' AND unit_no = '16' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 363 WHERE site_name = '삼우 2공장' AND unit_no = '16' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 364 WHERE site_name = '브이피에이치메탈' AND unit_no = '1' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 365 WHERE site_name = '명화공업(CPC)' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 366 WHERE site_name = '명화공업(CPC)' AND unit_no = '1' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 367 WHERE site_name = '명화공업-세명(COBA)' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 368 WHERE site_name = '명화공업-세명(COBA)' AND unit_no = '2' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 369 WHERE site_name = '울산 GPS' AND unit_no = '6' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 370 WHERE site_name = '울산 GPS' AND unit_no = '6' AND gas_name = 'NO 40ppm';
UPDATE calibration_gas_inventory SET sort_order = 371 WHERE site_name = '울산 GPS' AND unit_no = '6' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 372 WHERE site_name = '울산 GPS' AND unit_no = '7' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 373 WHERE site_name = '울산 GPS' AND unit_no = '7' AND gas_name = 'NO 40ppm';
UPDATE calibration_gas_inventory SET sort_order = 374 WHERE site_name = '울산 GPS' AND unit_no = '7' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 375 WHERE site_name = '울산 GPS' AND unit_no = '8' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 376 WHERE site_name = '울산 GPS' AND unit_no = '8' AND gas_name = 'NO 40ppm';
UPDATE calibration_gas_inventory SET sort_order = 377 WHERE site_name = '울산 GPS' AND unit_no = '8' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 378 WHERE site_name = '울산 GPS' AND unit_no = '9' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 379 WHERE site_name = '울산 GPS' AND unit_no = '9' AND gas_name = 'NO 40ppm';
UPDATE calibration_gas_inventory SET sort_order = 380 WHERE site_name = '울산 GPS' AND unit_no = '9' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 381 WHERE site_name = '코미코' AND unit_no = '1' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 382 WHERE site_name = '코미코' AND unit_no = '1' AND gas_name = 'NO 600ppm';
UPDATE calibration_gas_inventory SET sort_order = 383 WHERE site_name = '코미코' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 384 WHERE site_name = '한국가스공사 창원수소' AND unit_no = '1' AND gas_name = 'NO/O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 385 WHERE site_name = '한국가스공사 창원수소' AND unit_no = '1' AND gas_name = 'NO 500ppm';
UPDATE calibration_gas_inventory SET sort_order = 386 WHERE site_name = '한국가스공사 창원수소' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 387 WHERE site_name = '프린스페이퍼' AND unit_no = '1(비전송)' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 388 WHERE site_name = '프린스페이퍼' AND unit_no = '1(비전송)' AND gas_name = 'NO/SO2 200/200ppm (SO2 비전송)';
UPDATE calibration_gas_inventory SET sort_order = 389 WHERE site_name = '프린스페이퍼' AND unit_no = '1(비전송)' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 390 WHERE site_name = '프린스페이퍼' AND unit_no = '1(비전송)' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 391 WHERE site_name = '프린스페이퍼' AND unit_no = '1(비전송)' AND gas_name = 'Dust';
UPDATE calibration_gas_inventory SET sort_order = 392 WHERE site_name = '검단지역난방설비' AND unit_no = '1' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 393 WHERE site_name = '검단지역난방설비' AND unit_no = '1' AND gas_name = 'NO 100ppm';
UPDATE calibration_gas_inventory SET sort_order = 394 WHERE site_name = '검단지역난방설비' AND unit_no = '1' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 395 WHERE site_name = '검단지역난방설비' AND unit_no = '1' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 396 WHERE site_name = '검단지역난방설비' AND unit_no = '2' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 397 WHERE site_name = '검단지역난방설비' AND unit_no = '2' AND gas_name = 'NO 100ppm';
UPDATE calibration_gas_inventory SET sort_order = 398 WHERE site_name = '검단지역난방설비' AND unit_no = '2' AND gas_name = 'O2 Zero';
UPDATE calibration_gas_inventory SET sort_order = 399 WHERE site_name = '검단지역난방설비' AND unit_no = '2' AND gas_name = 'O2 25%';
UPDATE calibration_gas_inventory SET sort_order = 400 WHERE site_name = '한국 바스프 여수' AND unit_no = '' AND gas_name = '-';
UPDATE calibration_gas_inventory SET sort_order = 401 WHERE site_name = '앰코테크놀로지 송도' AND unit_no = '4,5' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 402 WHERE site_name = '앰코테크놀로지 송도' AND unit_no = '4,5' AND gas_name = 'NO 200ppm';
UPDATE calibration_gas_inventory SET sort_order = 403 WHERE site_name = '앰코테크놀로지 송도' AND unit_no = '4,5' AND gas_name = 'O2';
UPDATE calibration_gas_inventory SET sort_order = 404 WHERE site_name = '클린코리아 경주' AND unit_no = '' AND gas_name = 'NO Zero';
UPDATE calibration_gas_inventory SET sort_order = 405 WHERE site_name = '클린코리아 경주' AND unit_no = '' AND gas_name = 'NOx,SO2,CO';
UPDATE calibration_gas_inventory SET sort_order = 406 WHERE site_name = '클린코리아 경주' AND unit_no = '' AND gas_name = 'O2 25%';